### ISSUE TITLE
Bug: advanced chests

### ISSUE THREAD

**Issue by Souperhero** [Souperhero/Paradise-Island#7]
Throwing specials character errors

[10:31:04 ERROR]: Cannot load plugins\AdvancedChests\data\1a87c173-e9dc-4350-9e79-baf76c76eaf1.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed
in "'string'", position 0
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at us.lynuxcraft.deadsilenceiv.advancedchests.managers.yml.ChestsYamlStorage.a(ChestsYamlStorage.java:45) ~[AdvancedChests-22.7.jar:?]
        at us.lynuxcraft.deadsilenceiv.advancedchests.managers.yml.ChestsYamlStorage.<init>(ChestsYamlStorage.java:33) ~[AdvancedChests-22.7.jar:?]
        at us.lynuxcraft.deadsilenceiv.advancedchests.services.data.StorageType.getService(StorageType.java:19) ~[AdvancedChests-22.7.jar:?]
        at us.lynuxcraft.deadsilenceiv.advancedchests.managers.ChestsManager.<init>(ChestsManager.java:33) ~[AdvancedChests-22.7.jar:?]
        at us.lynuxcraft.deadsilenceiv.advancedchests.AdvancedChests.f(AdvancedChests.java:175) ~[AdvancedChests-22.7.jar:?]
        at us.lynuxcraft.deadsilenceiv.advancedchests.AdvancedChests.reloadPlugin(AdvancedChests.java:305) ~[AdvancedChests-22.7.jar:?]
        at us.lynuxcraft.deadsilenceiv.advancedchests.commands.MainCmd.onCommand(MainCmd.java:220) ~[AdvancedChests-22.7.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:140) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.17.1.jar:git-Airplane-"74774a0"]
        ... 32 more

**Comment by Souperhero** [comment]
worth.yml had two periods in front of some items.

closed
